### ISSUE TITLE
Error on model generation with rails

### ISSUE THREAD

**Issue by SPPBG** [CiaranAshton/BedMeApp#1]
Whenever I run,

`rails generate model SomeModel p1:type1 p2:type2 ... pN:typeN`

I get the following error.

`/usr/local/rvm/gems/ruby-2.3.0@railstutorial_rails_4_0/gems/guard-rspec-2.5.0/lib/guard/rspec.rb:2:in 'require': cannot load such file -- guard/guard (LoadError)`

This occurs when the gems, the Guard::Rspec in specific, from the last Gemfile are installed. No similar issues prior to this.

**Comment by CiaranAshton** [comment]
I think the issue is the gems need to be bundled? I will have a look if I get a chance later @SPPBG

**Comment by SPPBG** [comment]
I made sure all the gems were installed by bundler beforehand, otherwise it wouldn't allow me to generate new models.
